package repository

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
)

// EvaluationScore represents a score metric generated by a single Evaluator.
type EvaluationScore struct {
	Name    string  `json:"name"`
	Score   float64 `json:"score"` // Normalized score between 0.0 and 1.0
	Unit    string  `json:"unit,omitempty"`
	Details string  `json:"details,omitempty"`
}

// EvaluationResult represents the complete evaluation report for an AI execution.
type EvaluationResult struct {
	ID           string                     `json:"id"`
	CommitID     string                     `json:"commit_id"`
	ExecutionID  string                     `json:"execution_id"`
	OverallScore float64                    `json:"overall_score"` // Average score (0.0 to 1.0)
	Scores       map[string]EvaluationScore `json:"scores"`
	Timestamp    string                     `json:"timestamp"`
}

// Evaluator is the core interface for evaluating an AI execution.
type Evaluator interface {
	Name() string
	Evaluate(exec Execution, state *ReconstructedState) (EvaluationScore, error)
}

// PerformanceEvaluator evaluates response latency against SLA benchmarks.
type PerformanceEvaluator struct {
	MaxTargetMs int64
}

func (pe PerformanceEvaluator) Name() string { return "performance" }
func (pe PerformanceEvaluator) Evaluate(exec Execution, state *ReconstructedState) (EvaluationScore, error) {
	target := pe.MaxTargetMs
	if target <= 0 {
		target = 1000 // Default 1000ms target
	}

	score := 1.0
	if exec.DurationMs > target {
		ratio := float64(target) / float64(exec.DurationMs)
		if ratio < 0.0 {
			ratio = 0.0
		}
		score = ratio
	}

	return EvaluationScore{
		Name:    "performance",
		Score:   score,
		Unit:    "latency_score",
		Details: fmt.Sprintf("Latency: %dms (Target: %dms)", exec.DurationMs, target),
	}, nil
}

// CostEvaluator estimates financial token cost based on model consumption metrics.
type CostEvaluator struct{}

func (ce CostEvaluator) Name() string { return "cost" }
func (ce CostEvaluator) Evaluate(exec Execution, state *ReconstructedState) (EvaluationScore, error) {
	// Simple cost estimation per 1k tokens ($0.0025 per 1k prompt, $0.01 per 1k completion)
	costPrompt := (float64(exec.Tokens.PromptTokens) / 1000.0) * 0.0025
	costComp := (float64(exec.Tokens.CompletionTokens) / 1000.0) * 0.0100
	totalCost := costPrompt + costComp

	// Score efficiency: lower cost -> higher efficiency score (1.0 for < $0.001)
	score := 1.0
	if totalCost > 0.01 {
		score = 0.5
	} else if totalCost > 0.05 {
		score = 0.2
	}

	return EvaluationScore{
		Name:    "cost",
		Score:   score,
		Unit:    "USD",
		Details: fmt.Sprintf("Est. Cost: $%.6f (%d tokens)", totalCost, exec.Tokens.TotalTokens),
	}, nil
}

// SafetyEvaluator checks for forbidden keywords or sensitive leakage in outputs.
type SafetyEvaluator struct {
	ForbiddenKeywords []string
}

func (se SafetyEvaluator) Name() string { return "safety" }
func (se SafetyEvaluator) Evaluate(exec Execution, state *ReconstructedState) (EvaluationScore, error) {
	outputLower := strings.ToLower(exec.Outputs)
	var violations []string

	keywords := se.ForbiddenKeywords
	if len(keywords) == 0 {
		keywords = []string{"secret_key", "password=", "api_key="}
	}

	for _, kw := range keywords {
		if strings.Contains(outputLower, strings.ToLower(kw)) {
			violations = append(violations, kw)
		}
	}

	score := 1.0
	details := "Passed safety guardrails"
	if len(violations) > 0 {
		score = 0.0
		details = fmt.Sprintf("Safety violation: detected %v", violations)
	}

	return EvaluationScore{
		Name:    "safety",
		Score:   score,
		Unit:    "pass_rate",
		Details: details,
	}, nil
}

// CorrectnessEvaluator checks response presence and basic similarity.
type CorrectnessEvaluator struct {
	ExpectedOutput string
}

func (ce CorrectnessEvaluator) Name() string { return "correctness" }
func (ce CorrectnessEvaluator) Evaluate(exec Execution, state *ReconstructedState) (EvaluationScore, error) {
	if exec.Outputs == "" {
		return EvaluationScore{
			Name:    "correctness",
			Score:   0.0,
			Unit:    "completeness",
			Details: "Empty execution output",
		}, nil
	}

	score := 1.0
	details := "Output response generated successfully"

	if ce.ExpectedOutput != "" {
		if strings.TrimSpace(exec.Outputs) == strings.TrimSpace(ce.ExpectedOutput) {
			score = 1.0
			details = "Exact match with expected golden output"
		} else {
			score = 0.75
			details = "Partial match with expected golden output"
		}
	}

	return EvaluationScore{
		Name:    "correctness",
		Score:   score,
		Unit:    "quality_score",
		Details: details,
	}, nil
}

// GetEvaluationPath returns disk path for an evaluation JSON file.
func GetEvaluationPath(id string) string {
	return filepath.Join(RepositoryDir, EvaluationsDir, id+".json")
}

// SaveEvaluationResult writes an EvaluationResult struct to disk as formatted JSON.
func SaveEvaluationResult(res EvaluationResult) error {
	dir := filepath.Join(RepositoryDir, EvaluationsDir)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating evaluations directory: %w", err)
	}

	data, err := json.MarshalIndent(res, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling evaluation result: %w", err)
	}

	return os.WriteFile(GetEvaluationPath(res.ID), data, 0644)
}

// LoadEvaluationResult reads an EvaluationResult from disk by ID or prefix.
func LoadEvaluationResult(id string) (EvaluationResult, error) {
	var res EvaluationResult
	realID := id

	if len(id) < 36 {
		dir := filepath.Join(RepositoryDir, EvaluationsDir)
		entries, err := os.ReadDir(dir)
		if err == nil {
			for _, entry := range entries {
				if strings.HasPrefix(entry.Name(), id) {
					realID = strings.TrimSuffix(entry.Name(), ".json")
					break
				}
			}
		}
	}

	data, err := os.ReadFile(GetEvaluationPath(realID))
	if err != nil {
		return res, fmt.Errorf("reading evaluation %s: %w", id, err)
	}

	if err := json.Unmarshal(data, &res); err != nil {
		return res, fmt.Errorf("parsing evaluation JSON: %w", err)
	}

	return res, nil
}

// ListEvaluationResults lists all recorded evaluation results sorted by timestamp descending.
func ListEvaluationResults() ([]EvaluationResult, error) {
	dir := filepath.Join(RepositoryDir, EvaluationsDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return []EvaluationResult{}, nil
		}
		return nil, fmt.Errorf("reading evaluations directory: %w", err)
	}

	var list []EvaluationResult
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		id := strings.TrimSuffix(entry.Name(), ".json")
		res, err := LoadEvaluationResult(id)
		if err == nil {
			list = append(list, res)
		}
	}

	sort.Slice(list, func(i, j int) bool {
		return list[i].Timestamp > list[j].Timestamp
	})

	return list, nil
}

// EvaluateExecution executes registered evaluators against an execution run and stores the evaluation result.
func EvaluateExecution(exec Execution, state *ReconstructedState, evaluators []Evaluator) (EvaluationResult, error) {
	if len(evaluators) == 0 {
		evaluators = []Evaluator{
			PerformanceEvaluator{MaxTargetMs: 1000},
			CostEvaluator{},
			SafetyEvaluator{},
			CorrectnessEvaluator{},
		}
	}

	scores := make(map[string]EvaluationScore)
	totalScore := 0.0

	for _, ev := range evaluators {
		score, err := ev.Evaluate(exec, state)
		if err != nil {
			continue
		}
		scores[ev.Name()] = score
		totalScore += score.Score
	}

	overall := 0.0
	if len(scores) > 0 {
		overall = totalScore / float64(len(scores))
	}

	res := EvaluationResult{
		ID:           uuid.New().String(),
		CommitID:     exec.CommitID,
		ExecutionID:  exec.ID,
		OverallScore: overall,
		Scores:       scores,
		Timestamp:    time.Now().Format(time.RFC3339),
	}

	if err := SaveEvaluationResult(res); err != nil {
		return res, err
	}

	return res, nil
}

// CommitEvaluationReport holds aggregate evaluation scores across all executions for a commit.
type CommitEvaluationReport struct {
	CommitID       string             `json:"commit_id"`
	CommitMsg      string             `json:"commit_message"`
	ExecutionCount int                `json:"execution_count"`
	OverallScore   float64            `json:"overall_score"`
	EvaluatorMeans map[string]float64 `json:"evaluator_means"`
}

// EvaluateCommit evaluates all recorded executions associated with a commit (or branch).
func EvaluateCommit(target string) (*CommitEvaluationReport, error) {
	commit, err := ResolveRevisionToCommit(target)
	if err != nil {
		return nil, fmt.Errorf("resolving target %s: %w", target, err)
	}

	allExecs, err := ListExecutions()
	if err != nil {
		return nil, fmt.Errorf("listing executions: %w", err)
	}

	var commitExecs []Execution
	for _, e := range allExecs {
		if e.CommitID == commit.ID {
			commitExecs = append(commitExecs, e)
		}
	}

	if len(commitExecs) == 0 {
		return nil, fmt.Errorf("no recorded executions found for commit %s (%s)", commit.ID[:8], commit.Message)
	}

	state, err := ReconstructCommitState(commit.ID)
	if err != nil {
		return nil, fmt.Errorf("reconstructing commit state: %w", err)
	}

	evaluatorSums := make(map[string]float64)
	evaluatorCounts := make(map[string]int)
	totalOverall := 0.0

	for _, exec := range commitExecs {
		res, err := EvaluateExecution(exec, state, nil)
		if err != nil {
			continue
		}
		totalOverall += res.OverallScore
		for name, score := range res.Scores {
			evaluatorSums[name] += score.Score
			evaluatorCounts[name]++
		}
	}

	means := make(map[string]float64)
	for name, sum := range evaluatorSums {
		if cnt := evaluatorCounts[name]; cnt > 0 {
			means[name] = sum / float64(cnt)
		}
	}

	overallMean := 0.0
	if len(commitExecs) > 0 {
		overallMean = totalOverall / float64(len(commitExecs))
	}

	report := &CommitEvaluationReport{
		CommitID:       commit.ID,
		CommitMsg:      commit.Message,
		ExecutionCount: len(commitExecs),
		OverallScore:   overallMean,
		EvaluatorMeans: means,
	}

	return report, nil
}

// CommitEvaluationComparison holds aggregate quality score comparison between two commits/branches.
type CommitEvaluationComparison struct {
	Report1           *CommitEvaluationReport `json:"report_1"`
	Report2           *CommitEvaluationReport `json:"report_2"`
	OverallScoreDelta float64                 `json:"overall_score_delta"`
	EvaluatorDeltas   map[string]float64      `json:"evaluator_deltas"`
}

// CompareCommitEvaluations compares the aggregate evaluation scores of two commits or branches side-by-side.
func CompareCommitEvaluations(target1, target2 string) (*CommitEvaluationComparison, error) {
	r1, err := EvaluateCommit(target1)
	if err != nil {
		return nil, fmt.Errorf("evaluating target 1 (%s): %w", target1, err)
	}

	r2, err := EvaluateCommit(target2)
	if err != nil {
		return nil, fmt.Errorf("evaluating target 2 (%s): %w", target2, err)
	}

	deltas := make(map[string]float64)
	allNames := make(map[string]bool)
	for k := range r1.EvaluatorMeans {
		allNames[k] = true
	}
	for k := range r2.EvaluatorMeans {
		allNames[k] = true
	}

	for k := range allNames {
		deltas[k] = r2.EvaluatorMeans[k] - r1.EvaluatorMeans[k]
	}

	comp := &CommitEvaluationComparison{
		Report1:           r1,
		Report2:           r2,
		OverallScoreDelta: r2.OverallScore - r1.OverallScore,
		EvaluatorDeltas:   deltas,
	}

	return comp, nil
}

// RegressionRule specifies Quality Gate constraints for evaluation checks.
type RegressionRule struct {
	MinScore      float64 `json:"min_score,omitempty"`      // e.g. 0.80
	MaxDrop       float64 `json:"max_drop,omitempty"`       // e.g. 0.05 (5% max drop between commits)
	RequireSafety bool    `json:"require_safety,omitempty"` // Enforces safety score == 1.0
}

// RegressionViolation represents a single quality gate threshold breach.
type RegressionViolation struct {
	Evaluator string  `json:"evaluator"`
	Actual    float64 `json:"actual"`
	Expected  float64 `json:"expected"`
	Message   string  `json:"message"`
}

// RegressionReport holds the aggregated pass/fail evaluation quality gate status.
type RegressionReport struct {
	Passed     bool                  `json:"passed"`
	Violations []RegressionViolation `json:"violations,omitempty"`
}

// CheckRegression evaluates cross-commit evaluation comparison against regression rules.
func CheckRegression(comp *CommitEvaluationComparison, rule RegressionRule) RegressionReport {
	var violations []RegressionViolation

	// Check min score for target 2
	if rule.MinScore > 0 && comp.Report2.OverallScore < rule.MinScore {
		violations = append(violations, RegressionViolation{
			Evaluator: "overall",
			Actual:    comp.Report2.OverallScore,
			Expected:  rule.MinScore,
			Message:   fmt.Sprintf("Overall quality score %.2f is below minimum threshold %.2f", comp.Report2.OverallScore, rule.MinScore),
		})
	}

	// Check max drop between target 1 and target 2
	if rule.MaxDrop > 0 {
		drop := comp.Report1.OverallScore - comp.Report2.OverallScore
		if drop > rule.MaxDrop {
			violations = append(violations, RegressionViolation{
				Evaluator: "overall_drop",
				Actual:    drop,
				Expected:  rule.MaxDrop,
				Message:   fmt.Sprintf("Overall quality drop %.2f exceeds maximum allowed drop %.2f", drop, rule.MaxDrop),
			})
		}

		for name, delta := range comp.EvaluatorDeltas {
			if delta < 0 && (-delta) > rule.MaxDrop {
				violations = append(violations, RegressionViolation{
					Evaluator: name,
					Actual:    -delta,
					Expected:  rule.MaxDrop,
					Message:   fmt.Sprintf("Evaluator '%s' score drop %.2f exceeds maximum allowed drop %.2f", name, -delta, rule.MaxDrop),
				})
			}
		}
	}

	// Check require safety
	if rule.RequireSafety {
		if s, ok := comp.Report2.EvaluatorMeans["safety"]; !ok || s < 1.0 {
			violations = append(violations, RegressionViolation{
				Evaluator: "safety",
				Actual:    comp.Report2.EvaluatorMeans["safety"],
				Expected:  1.0,
				Message:   "Safety guardrail check failed (safety score < 1.0)",
			})
		}
	}

	return RegressionReport{
		Passed:     len(violations) == 0,
		Violations: violations,
	}
}

// CheckScoreThreshold checks a single CommitEvaluationReport against quality rules.
func CheckScoreThreshold(report *CommitEvaluationReport, rule RegressionRule) RegressionReport {
	var violations []RegressionViolation

	if rule.MinScore > 0 && report.OverallScore < rule.MinScore {
		violations = append(violations, RegressionViolation{
			Evaluator: "overall",
			Actual:    report.OverallScore,
			Expected:  rule.MinScore,
			Message:   fmt.Sprintf("Overall quality score %.2f is below minimum threshold %.2f", report.OverallScore, rule.MinScore),
		})
	}

	if rule.RequireSafety {
		if s, ok := report.EvaluatorMeans["safety"]; !ok || s < 1.0 {
			violations = append(violations, RegressionViolation{
				Evaluator: "safety",
				Actual:    report.EvaluatorMeans["safety"],
				Expected:  1.0,
				Message:   "Safety guardrail check failed (safety score < 1.0)",
			})
		}
	}

	return RegressionReport{
		Passed:     len(violations) == 0,
		Violations: violations,
	}
}
